-- 002_seed_demo_venues.sql
-- Popula public.venues com os seis estabelecimentos fictícios de demonstração
-- que já existem em src/data/venues.ts, para uso no piloto.
--
-- Estes seis locais são fictícios (mesma observação já presente em
-- src/data/venues.ts): endereços e números de WhatsApp são demonstrativos,
-- não correspondem a estabelecimentos reais.
--
-- Idempotente: usa ON CONFLICT (slug) DO UPDATE, então rodar este arquivo
-- mais de uma vez atualiza os mesmos seis registros em vez de duplicá-los.
-- Não altera a estrutura da tabela, policies ou RLS, e não usa DELETE,
-- TRUNCATE ou DROP.
--
-- O "id" de cada estabelecimento em src/data/venues.ts vira o "slug" aqui;
-- o "id" (uuid) da tabela continua gerado automaticamente pelo banco.
--
-- Nenhum dado foi inventado: nenhuma avaliação, lotação, número de
-- visualizações ou senso de urgência foi adicionado — só os campos que já
-- existiam no arquivo TypeScript de origem. data_confidence foi fixado em
-- 50 e is_published em true, conforme solicitado, independentemente dos
-- valores de "dataConfidence" usados na demonstração do app.

insert into public.venues (
  slug,
  name,
  city,
  neighborhood,
  address,
  category,
  description,
  cuisine_types,
  tags,
  music_styles,
  atmospheres,
  intentions,
  companions,
  menu_highlights,
  schedule,
  price_range,
  average_price_per_person,
  distance_km,
  whatsapp_number,
  data_confidence,
  is_published,
  updated_at
)
values
  (
    'pub-do-vale',
    'Pub do Vale',
    'São José dos Campos',
    'Vila Ema',
    'Rua Demonstrativa 120, Vila Ema - São José dos Campos, SP',
    'Bar & Pub',
    'Chopp artesanal, petiscos encorpados e música ao vivo em um ambiente descontraído para juntar a turma depois do trabalho.',
    array['Petiscos', 'Cozinha de boteco'],
    array['Chopp artesanal', 'Música ao vivo', 'Ambiente descontraído'],
    array['rock', 'mpb'],
    array['animado', 'casual'],
    array['amigos', 'musica-ao-vivo', 'comemorar', 'surpreenda'],
    array['amigos', 'casal'],
    array['Chopp Pilsen 500ml — R$ 18', 'Tábua de petiscos para dois — R$ 65', 'Burger artesanal do pub — R$ 42'],
    array['Sexta: Rock ao vivo às 21h', 'Sábado: Cover acústico às 20h'],
    '$$',
    70,
    6.5,
    '5512999110001',
    50,
    true,
    '2026-07-10'::timestamptz
  ),
  (
    'bella-serra',
    'Bella Serra',
    'São José dos Campos',
    'Jardim Aquarius',
    'Rua Demonstrativa 480, Jardim Aquarius - São José dos Campos, SP',
    'Restaurante Italiano',
    'Massas artesanais, carta de vinhos selecionada e iluminação intimista, perfeito para um jantar a dois sem pressa.',
    array['Italiana'],
    array['Culinária italiana', 'Ambiente romântico', 'Vinhos selecionados'],
    array['ambiente'],
    array['romantico', 'sofisticado'],
    array['casal', 'comemorar', 'surpreenda'],
    array['casal'],
    array['Tagliatelle ao ragù de cordeiro — R$ 89', 'Risoto de funghi — R$ 78', 'Taça de vinho tinto selecionado — R$ 38'],
    array['Terça a domingo: Jantar a partir das 19h'],
    '$$$',
    180,
    9.8,
    '5512999110002',
    50,
    true,
    '2026-07-12'::timestamptz
  ),
  (
    'rooftop-360',
    'Rooftop 360',
    'São José dos Campos',
    'Centro',
    'Rua Demonstrativa 10, Centro - São José dos Campos, SP',
    'Bar & Rooftop',
    'Vista panorâmica da cidade, drinks autorais e pôr do sol garantido. Ideal para comemorar ou simplesmente aproveitar a noite.',
    array['Drinks autorais', 'Contemporânea'],
    array['Vista panorâmica', 'Drinks autorais', 'Pôr do sol'],
    array['eletronica', 'mpb'],
    array['sofisticado', 'animado', 'romantico'],
    array['casal', 'comemorar', 'amigos', 'novidade', 'surpreenda'],
    array['casal', 'amigos'],
    array['Drink autoral com pôr do sol — R$ 34', 'Tábua de queijos e frios — R$ 72', 'Espumante nacional (taça) — R$ 29'],
    array['Quinta a sábado: DJ set às 22h'],
    '$$$',
    150,
    4.2,
    '5512999110003',
    50,
    true,
    '2026-07-14'::timestamptz
  ),
  (
    'cafe-aurora',
    'Café Aurora',
    'São José dos Campos',
    'Jardim Satélite',
    'Rua Demonstrativa 75, Jardim Satélite - São José dos Campos, SP',
    'Café & Brunch',
    'Brunch caprichado, café coado na hora e um pátio arborizado para relaxar sem pressa em qualquer dia da semana.',
    array['Cafeteria', 'Brunch'],
    array['Brunch', 'Ambiente tranquilo', 'Pet friendly'],
    array['ambiente'],
    array['tranquilo', 'casual', 'familiar'],
    array['relaxar', 'familia', 'novidade', 'surpreenda'],
    array['sozinho', 'casal', 'familia', 'amigos'],
    array['Brunch completo — R$ 39', 'Café coado da casa — R$ 12', 'Bolo de fubá com goiabada — R$ 16'],
    array['Todos os dias: Café da manhã e brunch até 12h'],
    '$',
    45,
    3.1,
    '5512999110004',
    50,
    true,
    '2026-07-13'::timestamptz
  ),
  (
    'quintal-da-familia',
    'Quintal da Família',
    'São José dos Campos',
    'Urbanova',
    'Rua Demonstrativa 900, Urbanova - São José dos Campos, SP',
    'Restaurante Familiar',
    'Espaço amplo com área externa, buffet variado e estrutura kids para reunir todas as gerações da família em um só lugar.',
    array['Brasileira', 'Buffet'],
    array['Espaço kids', 'Buffet variado', 'Área externa'],
    array['sertanejo', 'mpb'],
    array['familiar', 'casual'],
    array['familia', 'comemorar', 'surpreenda'],
    array['familia', 'amigos'],
    array['Buffet livre em família — R$ 59', 'Sobremesa infantil cortesia', 'Suco natural à vontade — R$ 14'],
    array['Domingo: Almoço em família das 12h às 16h'],
    '$$',
    65,
    12.4,
    '5512999110005',
    50,
    true,
    '2026-07-08'::timestamptz
  ),
  (
    'casa-do-rock',
    'Casa do Rock',
    'São José dos Campos',
    'Vila Adyana',
    'Rua Demonstrativa 33, Vila Adyana - São José dos Campos, SP',
    'Casa de Shows',
    'Bandas autorais, tributos e cerveja artesanal em um espaço feito para quem quer curtir uma boa música ao vivo.',
    array['Petiscos', 'Cervejaria'],
    array['Bandas autorais', 'Cerveja artesanal', 'Pista de dança'],
    array['rock'],
    array['animado', 'casual'],
    array['amigos', 'musica-ao-vivo', 'comemorar', 'novidade', 'surpreenda'],
    array['amigos', 'casal'],
    array['Cerveja artesanal IPA — R$ 24', 'Porção de isca de frango — R$ 48', 'Combo casal (2 chopps + porção) — R$ 89'],
    array['Sexta: Banda de rock nacional às 22h', 'Sábado: Tributo anos 80 às 21h'],
    '$$',
    90,
    18.5,
    '5512999110006',
    50,
    true,
    '2026-07-05'::timestamptz
  )
on conflict (slug) do update set
  name = excluded.name,
  city = excluded.city,
  neighborhood = excluded.neighborhood,
  address = excluded.address,
  category = excluded.category,
  description = excluded.description,
  cuisine_types = excluded.cuisine_types,
  tags = excluded.tags,
  music_styles = excluded.music_styles,
  atmospheres = excluded.atmospheres,
  intentions = excluded.intentions,
  companions = excluded.companions,
  menu_highlights = excluded.menu_highlights,
  schedule = excluded.schedule,
  price_range = excluded.price_range,
  average_price_per_person = excluded.average_price_per_person,
  distance_km = excluded.distance_km,
  whatsapp_number = excluded.whatsapp_number,
  data_confidence = excluded.data_confidence,
  is_published = excluded.is_published,
  updated_at = excluded.updated_at;
